function(ayugram_override_version file)
    file(STRINGS ${file} lines)
    foreach(line ${lines})
        if (line MATCHES "^AppVersionStrOfficial[ ]+([^ ]+)")
            set(official "${CMAKE_MATCH_1}")
        elseif (line MATCHES "^AppVersionStrSmall[ ]+([^ ]+)")
            set(display "${CMAKE_MATCH_1}")
        elseif (line MATCHES "^AppVersionStrFile[ ]+([^ ]+)")
            set(file_version "${CMAKE_MATCH_1}")
        elseif (line MATCHES "^AppUpdateVersion[ ]+([0-9]+)")
            set(update_version "${CMAKE_MATCH_1}")
        endif()
    endforeach()
    if (NOT DEFINED official
        OR NOT DEFINED display
        OR NOT DEFINED file_version
        OR NOT DEFINED update_version)
        message(FATAL_ERROR "AyuGram version fields are incomplete in ${file}")
    endif()

    string(REPLACE "." "," comma_version "${file_version}")
    set(desktop_app_version_string "${official}" PARENT_SCOPE)
    set(desktop_app_version_string_small "${display}" PARENT_SCOPE)
    set(desktop_app_version_dot "${file_version}" PARENT_SCOPE)
    set(desktop_app_version_comma "${comma_version}" PARENT_SCOPE)
    set(desktop_app_version_cmake "${file_version}" PARENT_SCOPE)
    set(desktop_app_version_int_alpha 0 PARENT_SCOPE)
    set(desktop_app_update_version "${update_version}" PARENT_SCOPE)
endfunction()
